Glossary
--------
[glossary]
CDA::
    Clinical Document Architecture -- an {hl7-home}[HL7] XML-based
    standard for clinical documents.
GENIA::
    A collection of biomedical literature. It has been
    compiled and annotated within the scope of the GENIA project.
    {genia-home}.
Orange Book::
    A list from the {fda-home}[U.S. Food and Drug Administrator] (FDA)
    of FDA approved prescription drugs, including new and generic
    drugs. {orangebook-home}.
Penn Treebank::
    Corpus of naturally-occuring text annotated for linguistic
    structure. {ptb-home}.
RxNORM::
    A ``standardized nomenclature for clinical drugs'', produced by
    the {nlm-home}[National Library of Medicine] (NLM). {rxnorm-home}.
SNOMED::
    Systematized Nomenclature of Medicine--Clinical Terms (SNOMED CT
    (R)) -- a comprehensive clinical terminology, originally created
    by the {cap-home}[College of American Pathologists] (CAP) and now,
    owned, maintained, and distributed by the
    {ihtsdo-home}[International Health Terminology Standards
    Development Organisation] (IHTSDO). {snomed-home}. See also
    {snomed-umls}.
UMLS::
    {nlm-home}[U.S. National Library of Medicine]'s Unified Medical
    Language System (R). {umls-home}.
