Conventions used in this guide
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The following typographical styles are used:

- `Monospace text` indicates file system paths or file names.
- `<Monospace text in angle brackets>` indicates file system paths or
  file names that should be replaced according to your computer's
  configuration or your preference.
- *`Bold monospace text`* indicates commands you need to type in the
  command line. For example,
+
--
__________________________________________________
+*java -cp <classpath> edu.mayo.uima.Class \ <1>
                     <arg1> \ <2>
                     <arg2>*+ <3>
__________________________________________________

<1> a command
<2> an argument
<3> another argument

We generally follow the Linux style. When it's not obvious to convert
to a Windows style, we provide both.
--
+
- File contents
+
----------------------------------------------
Monospace text enclosed in a box of this style
indicates contents in a file.
----------------------------------------------
+
- Sidebar note
+
****************************************************
Text enclosed in a box of this style
indicates a sidebar note, which you can safely skip.
****************************************************

The following images are used:

[NOTE]
.This is a note
=====
It contains additional information or remarks.
=====

[IMPORTANT]
.This is important
=====
Make sure you read this.
=====

[TIP]
.This is a tip
=====
It contains tips and tricks.
=====

