// Define some global attributes
include::_globattr.adoc[]

[[binary_install]]
Install the Binary Release
--------------------------
We provide an all-inclusive package for new users, and separate PEAR
packages for users to upgrade select components of the
{osp-short}. They can be found at {osp-download}. The source code can
also be downloaded following the link from the same site.
// In addition, we provide all the source code in the same web site.

This chapter guides you through installing the binary release and
processing an example clinical note.

TIP: If you don't know what 'binary' and 'source' are, you probably
would need to download the binary release.


Prerequisites
~~~~~~~~~~~~~
.Compiling from source
**********************************************************************
If you would like to compile from source, you may safely skip this
chapter, and go directly to <<compile_from_source>>.
**********************************************************************

{osp-short} requires Java version 1.5 (aka Java 5) or later and Apache
UIMA to run. You can get the latest version of Java from
{jre-download}, and Apache UIMA from {uima-download}. Please follow
their installation instructions.

TIP: The Apache UIMA documentation shows how to integrate it with
Eclipse. If you don't plan to develop your own code, just follow the
steps in  section ``{uima-install}'' of the UIMA documentation Book 1
``{uima-doc-book1}''.


Install from PEAR packages
~~~~~~~~~~~~~~~~~~~~~~~~~~
include::_extractpear.adoc[]

Process a sample clinical note
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
. Run
+
_____
*++cvd.bat -desc "{inst-root-dir}+++\clinical documents pipeline\clinical documents pipeline_pear.xml"+* (on Windows)
*+cvd.sh -desc \'{inst-root-dir}/clinical documents pipeline/clinical documents pipeline_pear.xml'+* (on Linux)
_____
+
from command line to start CAS Visual Debugger (CVD).
include::_testrun.adoc[]

NOTE: If UIMA's `bin` directory is not in your path, you'll need to
give the full path to `cvd.bat` or `cvd.sh`.

include::_postinstall.adoc[]
