/////
We provide two versions of source packages: one with UIMA PEAR files,
and one without. If you use the version without PEAR files, simply
extract the package to one directory, which we will call
+{inst-root-dir}+, and continue to the end of this section to install
required packages. Otherwise, please read the next paragraph.
/////


Download the main {osp-short} PEAR packages, from {osp-site}
(the latest {osp-short} version with +pear-bin+ in the name).
Extract all the PEAR files into a temporary
directory. Then follow ``{uima-pear-install}'' of the UIMA
documentation Book 3 ``{uima-doc-book3}'' to install all the PEAR
files, using the script in +UIMA_HOME/bin/runPearInstaller.sh+
(where +UIMA_HOME+ is the root directory of Apache UIMA).

When you install, make sure you use the same folder in the
Installation Directory box of the UIMA Pear Installer for all the PEAR
files. We'll refer to this folder as +{inst-root-dir}+ later.

.Installation order
[IMPORTANT]
=======================
Please install in the following order, otherwise you may experience
dependency errors.

. core
. document preprocessor
. POS tagger
. chunker
. context dependent tokenizer
. dictionary lookup
. LVG
. dependency parser (optional)
. NE contexts
. clinical documents pipeline
. PAD term spotter (optional)
. Drug NER (optional)

=======================

.Reminder - dictionaries
[NOTE]
===================================================================
Some of the dictionaries in the release are small samples. To
replace them with full versions, please read <<boost_performance>>.
===================================================================
